yaml
name: Katalon Test

on:
  push:
    branches:
      - master # Change this to your main branch

jobs:
  test:
    runs-on: windows

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Katalon
      uses: katalon-studio/cli-action@master
      with:
        version: '9.0' # Change this to the desired Katalon version

    - name: Run Katalon Tests
      run: |
        katalonc -noSplash -runMode=console -projectPath="pavanblast008@gmail.com:Iamgithub@123https://github.com/pavanblast/Katalon.git/project.prj" -retry=0 -testSuitePath="Test Suites/New Test Suite" -browserType="Chrome" -executionProfile="default" -apiKey="4d4ebb50-5677-4208-ae34-a833770d4ee8" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true -webui.autoUpdateDrivers=true
