<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_AI-powered1</name>
   <tag></tag>
   <elementGuidId>5dc96cd2-6ef4-42bf-8056-e75c29a17479</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.hyper_link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[text()='StudioAssist ']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0978e44e-0f3a-4e95-9d3f-8415efab1e48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hyper_link</value>
      <webElementGuid>04627c29-39ac-475a-91d0-9336f9c44146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ai-powered-testing-platform</value>
      <webElementGuid>518fe1bf-b2a7-44db-903a-4fe0c24abe1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>f88539ac-db4b-42a0-9e88-a3ab0ece1d23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AI-powered</value>
      <webElementGuid>4a0c6a3b-1433-45be-b91b-d74cb0ca86e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;HomePage_wrapHomePage__zdHwS&quot;]/section[@class=&quot;katalon_ai_section&quot;]/div[@class=&quot;ai_title&quot;]/a[@class=&quot;hyper_link&quot;]</value>
      <webElementGuid>827b70be-1837-4268-aea8-6484957a80fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/section[3]/div/a</value>
      <webElementGuid>0d464c3d-ce7c-4070-90ac-3a0b0e4baa5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'AI-powered')]</value>
      <webElementGuid>0116effd-3b6b-4a32-b31f-1c3e3859b7d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/ai-powered-testing-platform')])[3]</value>
      <webElementGuid>029e6552-c5f3-4a1b-abde-fc84bdf2e72f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div/a</value>
      <webElementGuid>e9f62a02-a805-479f-bcd3-2fe3c235f4c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/ai-powered-testing-platform' and (text() = 'AI-powered' or . = 'AI-powered')]</value>
      <webElementGuid>61ac0479-d3ca-4500-9401-97862563539d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
