<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_AI-powered</name>
   <tag></tag>
   <elementGuidId>97953624-1fdf-4635-a60c-96ece11ab055</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.hyper_link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[text()='Visual testing ']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fb5ea315-0961-490f-9175-bc7f926df50b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hyper_link</value>
      <webElementGuid>29b5fc48-4c40-4b16-8291-7f7a3518ccfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ai-powered-testing-platform</value>
      <webElementGuid>71f1b2aa-622d-4ff5-88f6-797614048a91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>926e2925-dae8-480b-b099-0dcb22c3e532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AI-powered</value>
      <webElementGuid>533afe87-d816-4c45-8f09-e73375dedfe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;HomePage_wrapHomePage__zdHwS&quot;]/section[@class=&quot;katalon_ai_section&quot;]/div[@class=&quot;ai_title&quot;]/a[@class=&quot;hyper_link&quot;]</value>
      <webElementGuid>a951a9ea-8199-4d81-8daf-e81ac44e9316</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/section[3]/div/a</value>
      <webElementGuid>3d6e5e6e-ad6c-40b9-83c4-8282a0932ac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'AI-powered')]</value>
      <webElementGuid>cd44e045-6d8c-478d-ab48-0f51ac87ed2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/ai-powered-testing-platform')])[3]</value>
      <webElementGuid>caaba555-38b6-463d-b885-7773d7fe8383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div/a</value>
      <webElementGuid>ea17ad88-677a-437f-aeef-4ab0efb222cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/ai-powered-testing-platform' and (text() = 'AI-powered' or . = 'AI-powered')]</value>
      <webElementGuid>616aba83-ffc2-479f-a4f5-db85135b0ae4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
