<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_My favourite colors are RedYellowBlueOrangeGreenPurple_color</name>
   <tag></tag>
   <elementGuidId>2d9c4e33-5b60-49fa-a421-cd22dd766582</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;color&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='color']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a727c345-6e94-4df7-b933-b7000216e419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0a8bc5e1-a5b1-4ce0-b69f-81ad11f715c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>color</value>
      <webElementGuid>311b4439-f1bf-4035-b385-d6c420326d0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>red</value>
      <webElementGuid>49d6fc25-e562-4450-93a2-d83fee1048c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Content&quot;)/div[@class=&quot;CenterCol&quot;]/blockquote[@class=&quot;Example&quot;]/form[1]/input[1]</value>
      <webElementGuid>5716011c-c46e-4e2d-8538-c92d1df7e0ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='color']</value>
      <webElementGuid>8c8f5d1b-c8a8-45aa-b11f-3bba1a3c4267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Content']/div/blockquote/form/input</value>
      <webElementGuid>ca967fc1-28c3-43bb-8964-0a09fa2cb477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>58eeb731-03d4-46ba-9b10-4228dbf44eba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'color']</value>
      <webElementGuid>2f45c9a4-08b4-4627-a5f9-a162e4a795b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
